### ISSUE TITLE
[Discussion] Should we provide some default bundle configuration ?

### ISSUE THREAD

**Issue by mickaelperrin** [forumone/wp-cfm#74]
I have organized my bundles in the following way. I would like to have your opinion on this, and if we should provide a default bundle configuration.

```
wpcfm_settings:
    bundles:
        -
            label: wpcfm
            name: wpcfm
            config:
                - wpcfm_settings
        -
            label: settings-general
            name: settings_general
            config:
                - admin_email
                - blogdescription
                - blogname
                - date_format
                - default_role
                - gmt_offset
                - start_of_week
                - time_format
                - timezone_string
                - users_can_register
        -
            label: settings-writing
            name: settings_writing
            config:
                - default_category
                - default_email_category
                - default_link_category
                - default_post_format
                - link_manager_enabled
                - mailserver_login
                - mailserver_pass
                - mailserver_url
                - ping_sites
                - use_balanceTags
                - use_smilies
        -
            label: settings-reading
            name: settings_reading
            config:
                - blog_charset
                - blog_public
                - page_for_posts
                - page_on_front
                - posts_per_page
                - posts_per_rss
                - rss_use_excerpt
                - show_on_front
        -
            label: settings-discussion
            name: settings_discussion
            config:
                - avatar_default
                - avatar_rating
                - blacklist_keys
                - close_comments_days_old
                - close_comments_for_old_posts
                - comment_max_links
                - comment_moderation
                - comment_order
                - comment_registration
                - comment_whitelist
                - comments_notify
                - comments_per_page
                - default_comment_status
                - default_comments_page
                - default_ping_status
                - default_pingback_flag
                - moderation_keys
                - moderation_notify
                - page_comments
                - require_name_email
                - show_avatars
                - thread_comments
                - thread_comments_depth
        -
            label: settings-medias
            name: settings_medias
            config:
                - image_default_align
                - image_default_link_type
                - image_default_size
                - large_size_h
                - large_size_w
                - medium_large_size_h
                - medium_large_size_w
                - medium_size_h
                - medium_size_w
                - thumbnail_crop
                - thumbnail_size_h
                - thumbnail_size_w
                - upload_path
                - upload_url_path
                - uploads_use_yearmonth_folders
        -
            label: settings-permalinks
            name: settings_permalinks
            config:
                - category_base
                - permalink_structure
                - tag_base
        -
            label: appearance-customize
            name: appearance_customize
            config:
                - site_icon
                - stylesheet
                - template
        -
            label: plugins
            name: plugins
            config:
                - active_plugins
                - recently_activated
                - recently_edited
                - uninstall_plugins
        -
            label: widgets
            name: widgets
            config:
                - sidebars_widgets
                - widget_archives
                - widget_calendar
                - widget_categories
                - widget_custom_html
                - widget_media_audio
                - widget_media_image
                - widget_media_video
                - widget_meta
                - widget_nav_menu
                - widget_pages
                - widget_recent-comments
                - widget_recent-posts
                - widget_rss
                - widget_search
                - widget_tag_cloud
                - widget_text
        -
            label: core
            name: core
            config:
                - can_compress_scripts
                - finished_splitting_shared_terms
                - fresh_site
                - hack_file
                - html_type
                - initial_db_version
                - links_updated_date_format
                - sticky_posts
                - use_trackback
        -
            label: taxonomy
            name: taxonomy
            config:
                - tax/category
                - tax/link_category
                - tax/nav_menu
                - tax/post_format
                - tax/post_tag
.label: wpcfm
.wpcfm_settings_format: json
```
